### ISSUE TITLE
Add boilerplate single line code 

### ISSUE THREAD

**Issue by aayushai** [aayushai/TranspilerX#11]
### example
- for Python`print "Hello World"`
- for Java `System.out.println("Hello World")`

**Comment by swarupn17** [comment]
Hey @aayushai please assign this to me.
Thanks

**Comment by thevashuydv** [comment]
@aayushai   submitted a Pull request for the same please review

**Comment by aayushai** [comment]
Go Ahead @swarupn17, 
@thevashuydv it'll be unfair to him if I merge your pr first, he asked first.

**Comment by thevashuydv** [comment]
okay @aayushai , please assign to me if he's not able to resolve

**Comment by swarupn17** [comment]
@aayushai I am doing this task. Please can you find any other issue.
Thanks!

**Comment by aayushai** [comment]
Yeah sure @thevashuydv I've assigned it, in the meantime, you can work on the new issue I am creating.
