### ISSUE TITLE
Add: . Dark and Light Mode Support

### ISSUE THREAD

**Issue by aayushai** [aayushai/TranspilerX#15]
#### Since I am already using a dark theme for Monaco Editor, extend the dark and light mode to the entire app for a cohesive look. Add a dark mode toggle button, making the UI more customizable.

**Comment by thevashuydv** [comment]
please assign to me @aayushai

**Comment by aayushai** [comment]
Sure! @thevashuydv

**Comment by thevashuydv** [comment]
tried switch the editor to light mode too, but I didn't look quite good

**Comment by aayushai** [comment]
@thevashuydv can you add previews of both the editor and whole page going light and dark mode also.

**Comment by thevashuydv** [comment]
@aayushai  sure

**Comment by thevashuydv** [comment]
![image](https://github.com/user-attachments/assets/6f205911-9b88-4089-b9fd-8c06efd35e8c)
![image](https://github.com/user-attachments/assets/ff21a7c9-685b-4457-85aa-d5efb2a6c7ab)
these were the light and dark modes

**Comment by thevashuydv** [comment]
@aayushai please tell which one look fine

**Comment by aayushai** [comment]
1. For the dark mode can you add the dark mode in the code editor conatiner where the Input Language text is coming and change the color of Input Language accordingly.
2. For the light mode don't make the whole editor white maintain a slightly pale shade of white for editor sector.
3. When in light mode also change the color of Convert button and the Cliploader if it is not visible.

**Comment by thevashuydv** [comment]
@aayushai  okayy

**Comment by thevashuydv** [comment]
raised a new pr , kindly review

**Comment by aayushai** [comment]
Hi @thevashuydv ,

Convert button is not visible in light mode and the code editor is set to white color, I asked to set it to a different shade like pale white or off-white.

**Comment by thevashuydv** [comment]
@aayushai  on it buddy

**Comment by thevashuydv** [comment]
@aayushai done buddy , kindly review

**Comment by aayushai** [comment]
@thevashuydv It has been merged.
