### ISSUE TITLE
Upgrade Form Controls

### ISSUE THREAD

**Issue by aayushai** [aayushai/TranspilerX#16]
### Action Items:

- Use `Headless UI` or any similar libraries for enhanced functionality.
- Add Tailwind-styled dropdowns for language selection.
- Ensure they are visually appealing and responsive.

**Comment by thevashuydv** [comment]
please assign to me @aayushai

**Comment by thevashuydv** [comment]
@aayushai can i work on this issue now?

**Comment by aayushai** [comment]
Go ahead

**Comment by thevashuydv** [comment]
@aayushai  can you provide some examples , how it should be done .

**Comment by aayushai** [comment]
@thevashuydv Use these libraries for form selector UI enhancement

[Radix-UI](https://www.radix-ui.com/)
[HeadlessUI](https://headlessui.com/)

**Comment by thevashuydv** [comment]
@aayushai  sure

**Comment by thevashuydv** [comment]
hey @aayushai does it look fine if I do the dropdown like this

![d1](https://github.com/user-attachments/assets/90b39d54-932b-40a8-9517-4b2f006f0932)
![d2](https://github.com/user-attachments/assets/a712a926-952c-4ab0-9ea1-0c5cc7cd24b4)

**Comment by aayushai** [comment]
@thevashuydv Try to use Headless UI, it's more clean.

**Comment by Rehannn03** [comment]
Hey @aayushai greetings!
Can you assign this task to me?

**Comment by aayushai** [comment]
Go Ahead @Rehannn03 .

**Comment by Rehannn03** [comment]
Thank You

**Comment by Rehannn03** [comment]
Hey @aayushai I have made the above changes and made a PR kindly review it.

**Comment by aayushai** [comment]
Yeah it's done. I've merged.

**Comment by Rehannn03** [comment]
Thank You!
