### ISSUE TITLE
Add Feedback for Empty Inputs

### ISSUE THREAD

**Issue by aayushai** [aayushai/TranspilerX#20]
### Description:
Give users clear feedback when they try to convert code with empty input fields. This could include a red warning message or a shake animation.

### Action Items:
- Add validation for empty input fields.
- Display a red warning message or apply a shake effect when conversion is attempted without input.

**Comment by thevashuydv** [comment]
@aayushai please assign

**Comment by thevashuydv** [comment]
@aayushai please review

**Comment by thevashuydv** [comment]
@aayushai  i have already raised a pr , thanks !

**Comment by thevashuydv** [comment]
@aayushai okay , i'll modify the code according to the requirement
