### ISSUE TITLE
Display: Input/Output Fields Vertically on Mobile View

### ISSUE THREAD

**Issue by aayushai** [aayushai/TranspilerX#3]
**Issue Description:**

In the current implementation, the input and output fields of the Monaco code editor are displayed side-by-side. While this layout works fine on larger screens, it causes a cramped view on mobile devices.

**Expected Behavior:**

On mobile devices, the input and output fields should be stacked vertically for better readability and ease of use.

**Desired Solution:**

Implement a responsive design that automatically switches the layout to display the input and output fields vertically when the screen width is less than 768px.

**Comment by Zish303** [comment]
@aayushai Please assign me this issue.

**Comment by aayushai** [comment]
Done.

**Comment by thevashuydv** [comment]
@aayushai i have submitted a pull request regarding this issue , kindly review it

**Comment by thevashuydv** [comment]
@aayushai can you add some more issues?

**Comment by aayushai** [comment]
@thevashuydv yeah i think the UI needs an upgrade and the code editor should also have code completion functionality. What do you think?
