### ISSUE TITLE
Add Toastify alert for empty input code

### ISSUE THREAD

**Issue by aayushai** [aayushai/TranspilerX#32]
### Description:
Give users clear feedback when they try to convert code with empty input fields. This could include a warning message using [Toastify](https://deadsimplechat.com/blog/react-toastify-the-complete-guide/)

### Action Items:
- Add validation for empty input fields.
- Display a warning message on top right when conversion is attempted without input.

**Comment by thevashuydv** [comment]
@aayushai please assign
