### ISSUE TITLE
adding the transpilerX logo on the webpage 

### ISSUE THREAD

**Issue by thevashuydv** [aayushai/TranspilerX#38]
hey @aayushai  was thinking about adding the transpilerX logo same as the favicon to the upperleft corner of the webpage

can you please add all the required labels for hacktoberfest and assign me this issue.
Thanks

**Comment by aayushai** [comment]
Okay but where are you making the log

**Comment by thevashuydv** [comment]
@aayushai i was thinking to use the same logo as you have in the favicon

**Comment by thevashuydv** [comment]
@aayushai ooh okay, i should close this then.
