### ISSUE TITLE
update readme file - tech stack

### ISSUE THREAD

**Issue by damarudhvarma** [aayushai/TranspilerX#49]
i want to upadte readme file tech stack regarding -

- ### storage : local storage
- ### styling libraries
-  ### and also some recently updated features .
if you have any other ideas for documenting in readme file tell Me. 

these are the things I want to modify  @aayushai can u please assign me this and add documentation and hactoberfest labels

**Comment by aayushai** [comment]
@damarudhvarma 
There's no need for that right now I am implementing some new features so I will change it myself.
